# -*- coding: utf-8 -*-
"""taller8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_RMfcUG12geak1Q2R79oV-k3IPsFtPS
"""

def formato_punto_flotante(numero):
    signo = '-' if numero < 0 else '+'
    valor_absoluto = abs(numero)
    exponente = 0

    while valor_absoluto >= 10:
        valor_absoluto /= 10
        exponente += 1

    while valor_absoluto < 1:
        valor_absoluto *= 10
        exponente -= 1

    return f"{signo}{valor_absoluto:.7f}e{exponente:+04d}"

def suma(num1, num2):
    resultado = num1 + num2
    return formato_punto_flotante(resultado)

def resta(num1, num2):
    resultado = num1 - num2
    return formato_punto_flotante(resultado)

def multiplicacion(num1, num2):
    resultado = num1 * num2
    return formato_punto_flotante(resultado)

def division(num1, num2):
    resultado = num1 / num2
    return formato_punto_flotante(resultado)

a = 75.20253
b = 0.009997
c = 533.075
d = 38.611007
e = 0.38654
f = 0.00012097
g = 37.86093
h = 0.000103862

resultado_a = suma(a, b)
resultado_b = resta(c, d)
resultado_c = multiplicacion(e, f)
resultado_d = division(g, h)

print("a) Suma:", resultado_a)
print("b) Resta:", resultado_b)
print("c) Multiplicación:", resultado_c)
print("d) División:", resultado_d)

