# -*- coding: utf-8 -*-
"""taller13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/155uIRw2mBNukLz815XvVPjZJ0_w01BzA
"""

import math

def taylor_approximation(x, n):
    approximation = 0
    for i in range(n + 1):
        approximation += (-1)**i * (x - 0.5)**i / math.factorial(i)
    return approximation

def true_value(x):
    return math.exp(-x)

def relative_approximation_error(true_val, approx_val):
    return abs((true_val - approx_val) / true_val) * 100

x_base = 0.5
x_target = 0.505

print("Orden\tAproximación\tError Relativo (%)")
for order in range(16):
    approx = taylor_approximation(x_target, order)
    true_val = true_value(x_target)
    error = relative_approximation_error(true_val, approx)
    print(f"{order}\t{approx:.10f}\t{error:.10f}%")