# -*- coding: utf-8 -*-
"""taller9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VIUHpA8F_pl03-3bR0xmqSFgApMi9mkz
"""

import math

def calcular_seno_aproximado(x, epsilon_s, max_iter):
    resultado_aprox = 0.0
    termino_actual = x
    i = 1

    while abs(termino_actual) > epsilon_s and i <= max_iter:
        resultado_aprox += termino_actual
        i += 1
        termino_actual = (-1) ** i * (x ** (2 * i + 1)) / math.factorial(2 * i + 1)

    error_aprox_rel_porcentual = abs((math.sin(x) - resultado_aprox) / math.sin(x)) * 100

    return resultado_aprox, error_aprox_rel_porcentual, i - 1

valor_radianes = float(input("Ingrese el valor en radianes: "))
epsilon_s = float(input("Ingrese el criterio de error esperado (epsilon_s): "))
max_iter = int(input("Ingrese el número máximo de iteraciones: "))

resultado, error_rel_porcentual, num_iteraciones = calcular_seno_aproximado(valor_radianes, epsilon_s, max_iter)

print(f"Valor estimado del seno: {resultado}")
print(f"Error aproximado relativo porcentual: {error_rel_porcentual:.8f}%")
print(f"Número de iteraciones realizadas: {num_iteraciones}")