# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1hczqaP6aNEFtl_sAw1wxBkJIbYgcU_
"""

import numpy as np

data = np.array([
    [1, 0, 0.6],
    [1, 1, 2],
    [2, 1, 0.1],
    [3, 2, 0.3],
    [1, 2, 2.2],
    [2, 3, 2.3],
    [3, 3, 0.8],
    [3, 1, -1]
])

x = data[:, :2]
y = data[:, 2]

x = np.column_stack((np.ones(x.shape[0]), x))

coefficients = np.linalg.lstsq(x, y, rcond=None)[0]


y_pred = np.dot(x, coefficients)

correlation_matrix = np.corrcoef(y, y_pred)
correlation = correlation_matrix[0, 1]

print("Coeficientes del ajuste lineal:")
print("a =", coefficients[0])
print("b =", coefficients[1])
print("Coeficiente de correlación (r):", correlation)